apiVersion: v1
kind: Service
metadata:
  name: cowweb
spec:
  type: {{ if .Values.ingress.enabled }}ClusterIP{{ else }}NodePort{{ end }}
  selector:
    app: cowweb
  ports:
  - name: http
    {{ if .Values.ingress.enabled }}
    port: {{ .Values.http.port | default 80 }}
    targetPort: {{ .Values.http.targetPort | default 8080 }}
    {{ else }}
    port: {{ .Values.http.port | default 8080 }}
    nodePort: {{ .Values.http.nodePort | default 30080 }}
    {{ end }}
    {{ if .Values.debug.enabled }}
  - name: debug
    port: {{ .Values.debug.port | default 8081 }}
    nodePort: {{ .Values.debug.nodePort | default 30081 }}
    {{ end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cowweb
  labels:
    app: cowweb
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cowweb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cowweb
    spec:
      containers:
      - name: cowweb
        image: {{ .Values.image }}
        ports:
        - name: api
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /cowsay/ping
            port: api
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /cowsay/ping
            port: api
          initialDelaySeconds: 15
          periodSeconds: 20
